version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - react-build:/app/build

  nginx:
    image: nginx:alpine
    volumes:
      - react-build:/usr/share/nginx/html
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - react-app

volumes:
  react-build:
